#
#  Author: Hari Sekhon
#  Date: 2022-02-18 18:35:04 +0000 (Fri, 18 Feb 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Actions-Test
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Dump Contexts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  validate:
    if: github.repository_owner == 'HariSekhon'
    name: Dump Contexts
    uses: HariSekhon/GitHub-Actions/.github/workflows/dump_contexts.yaml@master
